<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class AddPatientMaster
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Me.Label1 = New System.Windows.Forms.Label()
        Me.Label3 = New System.Windows.Forms.Label()
        Me.Label4 = New System.Windows.Forms.Label()
        Me.Label5 = New System.Windows.Forms.Label()
        Me.Label6 = New System.Windows.Forms.Label()
        Me.Label7 = New System.Windows.Forms.Label()
        Me.Label8 = New System.Windows.Forms.Label()
        Me.Label9 = New System.Windows.Forms.Label()
        Me.Label10 = New System.Windows.Forms.Label()
        Me.Label11 = New System.Windows.Forms.Label()
        Me.Label12 = New System.Windows.Forms.Label()
        Me.Label13 = New System.Windows.Forms.Label()
        Me.Label14 = New System.Windows.Forms.Label()
        Me.Label15 = New System.Windows.Forms.Label()
        Me.Label2 = New System.Windows.Forms.Label()
        Me.Label17 = New System.Windows.Forms.Label()
        Me.Label18 = New System.Windows.Forms.Label()
        Me.ddcenter = New System.Windows.Forms.ComboBox()
        Me.ddcountry = New System.Windows.Forms.ComboBox()
        Me.ddstate = New System.Windows.Forms.ComboBox()
        Me.dddist = New System.Windows.Forms.ComboBox()
        Me.ddregdoct = New System.Windows.Forms.ComboBox()
        Me.ddrefdoct = New System.Windows.Forms.ComboBox()
        Me.ddsource = New System.Windows.Forms.ComboBox()
        Me.ddgenerated = New System.Windows.Forms.ComboBox()
        Me.ddsex = New System.Windows.Forms.ComboBox()
        Me.txtoldid = New System.Windows.Forms.TextBox()
        Me.txtname = New System.Windows.Forms.TextBox()
        Me.txtaddress = New System.Windows.Forms.TextBox()
        Me.txtphoneno = New System.Windows.Forms.TextBox()
        Me.dtreg = New System.Windows.Forms.DateTimePicker()
        Me.dtdob = New System.Windows.Forms.DateTimePicker()
        Me.GroupBox1 = New System.Windows.Forms.GroupBox()
        Me.btncancel = New System.Windows.Forms.Button()
        Me.btnsave = New System.Windows.Forms.Button()
        Me.txtage = New System.Windows.Forms.TextBox()
        Me.GroupBox1.SuspendLayout()
        Me.SuspendLayout()
        '
        'Label1
        '
        Me.Label1.BackColor = System.Drawing.Color.LightSlateGray
        Me.Label1.Dock = System.Windows.Forms.DockStyle.Top
        Me.Label1.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Label1.ForeColor = System.Drawing.Color.Yellow
        Me.Label1.Location = New System.Drawing.Point(0, 0)
        Me.Label1.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
        Me.Label1.Name = "Label1"
        Me.Label1.Size = New System.Drawing.Size(672, 23)
        Me.Label1.TabIndex = 0
        Me.Label1.Text = "Patient Master Form"
        Me.Label1.TextAlign = System.Drawing.ContentAlignment.TopCenter
        '
        'Label3
        '
        Me.Label3.ForeColor = System.Drawing.SystemColors.ActiveCaptionText
        Me.Label3.Location = New System.Drawing.Point(367, 223)
        Me.Label3.Name = "Label3"
        Me.Label3.Size = New System.Drawing.Size(72, 20)
        Me.Label3.TabIndex = 2
        Me.Label3.Text = "State"
        '
        'Label4
        '
        Me.Label4.ForeColor = System.Drawing.SystemColors.ActiveCaptionText
        Me.Label4.Location = New System.Drawing.Point(29, 257)
        Me.Label4.Name = "Label4"
        Me.Label4.Size = New System.Drawing.Size(89, 20)
        Me.Label4.TabIndex = 3
        Me.Label4.Text = "District"
        '
        'Label5
        '
        Me.Label5.ForeColor = System.Drawing.SystemColors.ActiveCaptionText
        Me.Label5.Location = New System.Drawing.Point(29, 381)
        Me.Label5.Name = "Label5"
        Me.Label5.Size = New System.Drawing.Size(89, 20)
        Me.Label5.TabIndex = 4
        Me.Label5.Text = "Generated BY"
        '
        'Label6
        '
        Me.Label6.ForeColor = System.Drawing.SystemColors.ActiveCaptionText
        Me.Label6.Location = New System.Drawing.Point(29, 351)
        Me.Label6.Name = "Label6"
        Me.Label6.Size = New System.Drawing.Size(149, 20)
        Me.Label6.TabIndex = 5
        Me.Label6.Text = "Source of Information"
        '
        'Label7
        '
        Me.Label7.ForeColor = System.Drawing.SystemColors.ActiveCaptionText
        Me.Label7.Location = New System.Drawing.Point(29, 321)
        Me.Label7.Name = "Label7"
        Me.Label7.Size = New System.Drawing.Size(149, 20)
        Me.Label7.TabIndex = 6
        Me.Label7.Text = "Referred by Doctor"
        '
        'Label8
        '
        Me.Label8.ForeColor = System.Drawing.SystemColors.ActiveCaptionText
        Me.Label8.Location = New System.Drawing.Point(29, 291)
        Me.Label8.Name = "Label8"
        Me.Label8.Size = New System.Drawing.Size(149, 20)
        Me.Label8.TabIndex = 7
        Me.Label8.Text = "Registered For Doctor"
        '
        'Label9
        '
        Me.Label9.ForeColor = System.Drawing.SystemColors.ActiveCaptionText
        Me.Label9.Location = New System.Drawing.Point(29, 227)
        Me.Label9.Name = "Label9"
        Me.Label9.Size = New System.Drawing.Size(89, 20)
        Me.Label9.TabIndex = 8
        Me.Label9.Text = "Country"
        '
        'Label10
        '
        Me.Label10.ForeColor = System.Drawing.SystemColors.ActiveCaptionText
        Me.Label10.Location = New System.Drawing.Point(29, 194)
        Me.Label10.Name = "Label10"
        Me.Label10.Size = New System.Drawing.Size(89, 20)
        Me.Label10.TabIndex = 9
        Me.Label10.Text = "Phone No."
        '
        'Label11
        '
        Me.Label11.ForeColor = System.Drawing.SystemColors.ActiveCaptionText
        Me.Label11.Location = New System.Drawing.Point(29, 160)
        Me.Label11.Name = "Label11"
        Me.Label11.Size = New System.Drawing.Size(89, 20)
        Me.Label11.TabIndex = 10
        Me.Label11.Text = "Address"
        '
        'Label12
        '
        Me.Label12.ForeColor = System.Drawing.SystemColors.ActiveCaptionText
        Me.Label12.Location = New System.Drawing.Point(421, 128)
        Me.Label12.Name = "Label12"
        Me.Label12.Size = New System.Drawing.Size(89, 20)
        Me.Label12.TabIndex = 11
        Me.Label12.Text = "Age (Years)"
        '
        'Label13
        '
        Me.Label13.ForeColor = System.Drawing.SystemColors.ActiveCaptionText
        Me.Label13.Location = New System.Drawing.Point(195, 128)
        Me.Label13.Name = "Label13"
        Me.Label13.Size = New System.Drawing.Size(89, 20)
        Me.Label13.TabIndex = 12
        Me.Label13.Text = "Date of Birth"
        '
        'Label14
        '
        Me.Label14.ForeColor = System.Drawing.SystemColors.ActiveCaptionText
        Me.Label14.Location = New System.Drawing.Point(29, 128)
        Me.Label14.Name = "Label14"
        Me.Label14.Size = New System.Drawing.Size(89, 20)
        Me.Label14.TabIndex = 13
        Me.Label14.Text = "Sex"
        '
        'Label15
        '
        Me.Label15.ForeColor = System.Drawing.SystemColors.ActiveCaptionText
        Me.Label15.Location = New System.Drawing.Point(29, 32)
        Me.Label15.Name = "Label15"
        Me.Label15.Size = New System.Drawing.Size(89, 20)
        Me.Label15.TabIndex = 14
        Me.Label15.Text = "Patient ID"
        '
        'Label2
        '
        Me.Label2.ForeColor = System.Drawing.SystemColors.ActiveCaptionText
        Me.Label2.Location = New System.Drawing.Point(381, 32)
        Me.Label2.Name = "Label2"
        Me.Label2.Size = New System.Drawing.Size(89, 20)
        Me.Label2.TabIndex = 16
        Me.Label2.Text = "Old ID"
        '
        'Label17
        '
        Me.Label17.ForeColor = System.Drawing.SystemColors.ActiveCaptionText
        Me.Label17.Location = New System.Drawing.Point(29, 62)
        Me.Label17.Name = "Label17"
        Me.Label17.Size = New System.Drawing.Size(149, 20)
        Me.Label17.TabIndex = 17
        Me.Label17.Text = "Date of Registration"
        '
        'Label18
        '
        Me.Label18.ForeColor = System.Drawing.SystemColors.ActiveCaptionText
        Me.Label18.Location = New System.Drawing.Point(29, 93)
        Me.Label18.Name = "Label18"
        Me.Label18.Size = New System.Drawing.Size(89, 20)
        Me.Label18.TabIndex = 18
        Me.Label18.Text = "Full Name"
        '
        'ddcenter
        '
        Me.ddcenter.FormattingEnabled = True
        Me.ddcenter.Items.AddRange(New Object() {"ATC", "ARC"})
        Me.ddcenter.Location = New System.Drawing.Point(125, 32)
        Me.ddcenter.Name = "ddcenter"
        Me.ddcenter.Size = New System.Drawing.Size(53, 24)
        Me.ddcenter.TabIndex = 19
        '
        'ddcountry
        '
        Me.ddcountry.FormattingEnabled = True
        Me.ddcountry.Location = New System.Drawing.Point(213, 223)
        Me.ddcountry.Name = "ddcountry"
        Me.ddcountry.Size = New System.Drawing.Size(96, 24)
        Me.ddcountry.TabIndex = 20
        '
        'ddstate
        '
        Me.ddstate.FormattingEnabled = True
        Me.ddstate.Location = New System.Drawing.Point(445, 223)
        Me.ddstate.Name = "ddstate"
        Me.ddstate.Size = New System.Drawing.Size(152, 24)
        Me.ddstate.TabIndex = 21
        '
        'dddist
        '
        Me.dddist.FormattingEnabled = True
        Me.dddist.Location = New System.Drawing.Point(213, 257)
        Me.dddist.Name = "dddist"
        Me.dddist.Size = New System.Drawing.Size(273, 24)
        Me.dddist.TabIndex = 22
        '
        'ddregdoct
        '
        Me.ddregdoct.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.ddregdoct.FormattingEnabled = True
        Me.ddregdoct.Location = New System.Drawing.Point(213, 287)
        Me.ddregdoct.Name = "ddregdoct"
        Me.ddregdoct.Size = New System.Drawing.Size(273, 24)
        Me.ddregdoct.TabIndex = 23
        '
        'ddrefdoct
        '
        Me.ddrefdoct.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.ddrefdoct.FormattingEnabled = True
        Me.ddrefdoct.Location = New System.Drawing.Point(213, 317)
        Me.ddrefdoct.Name = "ddrefdoct"
        Me.ddrefdoct.Size = New System.Drawing.Size(273, 24)
        Me.ddrefdoct.TabIndex = 24
        '
        'ddsource
        '
        Me.ddsource.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.ddsource.FormattingEnabled = True
        Me.ddsource.Items.AddRange(New Object() {"1", "2", "3", "4"})
        Me.ddsource.Location = New System.Drawing.Point(213, 347)
        Me.ddsource.Name = "ddsource"
        Me.ddsource.Size = New System.Drawing.Size(273, 24)
        Me.ddsource.TabIndex = 25
        '
        'ddgenerated
        '
        Me.ddgenerated.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.ddgenerated.FormattingEnabled = True
        Me.ddgenerated.Items.AddRange(New Object() {"1", "2", "3"})
        Me.ddgenerated.Location = New System.Drawing.Point(213, 381)
        Me.ddgenerated.Name = "ddgenerated"
        Me.ddgenerated.Size = New System.Drawing.Size(273, 24)
        Me.ddgenerated.TabIndex = 26
        '
        'ddsex
        '
        Me.ddsex.FormattingEnabled = True
        Me.ddsex.Items.AddRange(New Object() {"Male", "Female"})
        Me.ddsex.Location = New System.Drawing.Point(124, 128)
        Me.ddsex.Name = "ddsex"
        Me.ddsex.Size = New System.Drawing.Size(53, 24)
        Me.ddsex.TabIndex = 27
        '
        'txtoldid
        '
        Me.txtoldid.Location = New System.Drawing.Point(445, 31)
        Me.txtoldid.Name = "txtoldid"
        Me.txtoldid.Size = New System.Drawing.Size(100, 23)
        Me.txtoldid.TabIndex = 28
        '
        'txtname
        '
        Me.txtname.Location = New System.Drawing.Point(213, 90)
        Me.txtname.Name = "txtname"
        Me.txtname.Size = New System.Drawing.Size(316, 23)
        Me.txtname.TabIndex = 29
        '
        'txtaddress
        '
        Me.txtaddress.Location = New System.Drawing.Point(213, 160)
        Me.txtaddress.Multiline = True
        Me.txtaddress.Name = "txtaddress"
        Me.txtaddress.Size = New System.Drawing.Size(316, 28)
        Me.txtaddress.TabIndex = 30
        '
        'txtphoneno
        '
        Me.txtphoneno.Location = New System.Drawing.Point(213, 194)
        Me.txtphoneno.Name = "txtphoneno"
        Me.txtphoneno.Size = New System.Drawing.Size(100, 23)
        Me.txtphoneno.TabIndex = 31
        '
        'dtreg
        '
        Me.dtreg.Format = System.Windows.Forms.DateTimePickerFormat.[Short]
        Me.dtreg.Location = New System.Drawing.Point(213, 62)
        Me.dtreg.Name = "dtreg"
        Me.dtreg.Size = New System.Drawing.Size(118, 23)
        Me.dtreg.TabIndex = 32
        '
        'dtdob
        '
        Me.dtdob.Format = System.Windows.Forms.DateTimePickerFormat.[Short]
        Me.dtdob.Location = New System.Drawing.Point(277, 126)
        Me.dtdob.Name = "dtdob"
        Me.dtdob.Size = New System.Drawing.Size(119, 23)
        Me.dtdob.TabIndex = 33
        '
        'GroupBox1
        '
        Me.GroupBox1.BackColor = System.Drawing.Color.DarkCyan
        Me.GroupBox1.Controls.Add(Me.btncancel)
        Me.GroupBox1.Controls.Add(Me.btnsave)
        Me.GroupBox1.Location = New System.Drawing.Point(88, 420)
        Me.GroupBox1.Margin = New System.Windows.Forms.Padding(0)
        Me.GroupBox1.Name = "GroupBox1"
        Me.GroupBox1.Padding = New System.Windows.Forms.Padding(0)
        Me.GroupBox1.Size = New System.Drawing.Size(494, 51)
        Me.GroupBox1.TabIndex = 34
        Me.GroupBox1.TabStop = False
        '
        'btncancel
        '
        Me.btncancel.BackColor = System.Drawing.Color.DeepSkyBlue
        Me.btncancel.FlatStyle = System.Windows.Forms.FlatStyle.Popup
        Me.btncancel.Location = New System.Drawing.Point(243, 19)
        Me.btncancel.Name = "btncancel"
        Me.btncancel.Size = New System.Drawing.Size(75, 26)
        Me.btncancel.TabIndex = 1
        Me.btncancel.Text = "Cancel"
        Me.btncancel.UseVisualStyleBackColor = False
        '
        'btnsave
        '
        Me.btnsave.BackColor = System.Drawing.Color.DeepSkyBlue
        Me.btnsave.FlatStyle = System.Windows.Forms.FlatStyle.Popup
        Me.btnsave.Location = New System.Drawing.Point(162, 19)
        Me.btnsave.Name = "btnsave"
        Me.btnsave.Size = New System.Drawing.Size(75, 26)
        Me.btnsave.TabIndex = 0
        Me.btnsave.Text = "Save"
        Me.btnsave.UseVisualStyleBackColor = False
        '
        'txtage
        '
        Me.txtage.Location = New System.Drawing.Point(516, 128)
        Me.txtage.Name = "txtage"
        Me.txtage.Size = New System.Drawing.Size(66, 23)
        Me.txtage.TabIndex = 35
        '
        'AddPatientMaster
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(8.0!, 16.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.BackColor = System.Drawing.Color.SkyBlue
        Me.ClientSize = New System.Drawing.Size(672, 479)
        Me.Controls.Add(Me.txtage)
        Me.Controls.Add(Me.GroupBox1)
        Me.Controls.Add(Me.dtdob)
        Me.Controls.Add(Me.dtreg)
        Me.Controls.Add(Me.txtphoneno)
        Me.Controls.Add(Me.txtaddress)
        Me.Controls.Add(Me.txtname)
        Me.Controls.Add(Me.txtoldid)
        Me.Controls.Add(Me.ddsex)
        Me.Controls.Add(Me.ddgenerated)
        Me.Controls.Add(Me.ddsource)
        Me.Controls.Add(Me.ddrefdoct)
        Me.Controls.Add(Me.ddregdoct)
        Me.Controls.Add(Me.dddist)
        Me.Controls.Add(Me.ddstate)
        Me.Controls.Add(Me.ddcountry)
        Me.Controls.Add(Me.ddcenter)
        Me.Controls.Add(Me.Label18)
        Me.Controls.Add(Me.Label17)
        Me.Controls.Add(Me.Label2)
        Me.Controls.Add(Me.Label15)
        Me.Controls.Add(Me.Label14)
        Me.Controls.Add(Me.Label13)
        Me.Controls.Add(Me.Label12)
        Me.Controls.Add(Me.Label11)
        Me.Controls.Add(Me.Label10)
        Me.Controls.Add(Me.Label9)
        Me.Controls.Add(Me.Label8)
        Me.Controls.Add(Me.Label7)
        Me.Controls.Add(Me.Label6)
        Me.Controls.Add(Me.Label5)
        Me.Controls.Add(Me.Label4)
        Me.Controls.Add(Me.Label3)
        Me.Controls.Add(Me.Label1)
        Me.Font = New System.Drawing.Font("Microsoft Sans Serif", 10.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.ForeColor = System.Drawing.SystemColors.ButtonHighlight
        Me.Margin = New System.Windows.Forms.Padding(4)
        Me.Name = "AddPatientMaster"
        Me.Text = "Add Patient Master"
        Me.WindowState = System.Windows.Forms.FormWindowState.Maximized
        Me.GroupBox1.ResumeLayout(False)
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
    Friend WithEvents Label1 As System.Windows.Forms.Label
    Friend WithEvents Label3 As System.Windows.Forms.Label
    Friend WithEvents Label4 As System.Windows.Forms.Label
    Friend WithEvents Label5 As System.Windows.Forms.Label
    Friend WithEvents Label6 As System.Windows.Forms.Label
    Friend WithEvents Label7 As System.Windows.Forms.Label
    Friend WithEvents Label8 As System.Windows.Forms.Label
    Friend WithEvents Label9 As System.Windows.Forms.Label
    Friend WithEvents Label10 As System.Windows.Forms.Label
    Friend WithEvents Label11 As System.Windows.Forms.Label
    Friend WithEvents Label12 As System.Windows.Forms.Label
    Friend WithEvents Label13 As System.Windows.Forms.Label
    Friend WithEvents Label14 As System.Windows.Forms.Label
    Friend WithEvents Label15 As System.Windows.Forms.Label
    Friend WithEvents Label2 As System.Windows.Forms.Label
    Friend WithEvents Label17 As System.Windows.Forms.Label
    Friend WithEvents Label18 As System.Windows.Forms.Label
    Friend WithEvents ddcenter As System.Windows.Forms.ComboBox
    Friend WithEvents ddcountry As System.Windows.Forms.ComboBox
    Friend WithEvents ddstate As System.Windows.Forms.ComboBox
    Friend WithEvents dddist As System.Windows.Forms.ComboBox
    Friend WithEvents ddregdoct As System.Windows.Forms.ComboBox
    Friend WithEvents ddrefdoct As System.Windows.Forms.ComboBox
    Friend WithEvents ddsource As System.Windows.Forms.ComboBox
    Friend WithEvents ddgenerated As System.Windows.Forms.ComboBox
    Friend WithEvents ddsex As System.Windows.Forms.ComboBox
    Friend WithEvents txtoldid As System.Windows.Forms.TextBox
    Friend WithEvents txtname As System.Windows.Forms.TextBox
    Friend WithEvents txtaddress As System.Windows.Forms.TextBox
    Friend WithEvents txtphoneno As System.Windows.Forms.TextBox
    Friend WithEvents dtreg As System.Windows.Forms.DateTimePicker
    Friend WithEvents dtdob As System.Windows.Forms.DateTimePicker
    Friend WithEvents GroupBox1 As System.Windows.Forms.GroupBox
    Friend WithEvents btncancel As System.Windows.Forms.Button
    Friend WithEvents btnsave As System.Windows.Forms.Button
    Friend WithEvents txtage As System.Windows.Forms.TextBox
End Class
